# Generated by Django 4.2 on 2024-05-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_category'),
        ('articles', '0002_article_view_count_alter_article_category'),
    ]

    operations = [
    ]
