# Generated by Django 4.2 on 2024-05-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_v1iew_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='v1iew_count',
        ),
    ]
